name: tekartik_html
version: 0.3.1
description: An html abstraction layer to work with both dart:html and the html package
homepage: https://github.com/tekartik/tekartik_html.dart
publish_to: none

environment:
  sdk: ^3.4.0
dependencies:
  args:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.7'
  html: '>=0.15.0'
  web: '>=0.5.0'

dev_dependencies:
  test: '>=1.0.0'
  dev_build:
  process_run: '>=0.10.3'
  build_runner: '>=1.11.5'
  build_web_compilers: '>=2.16.4'
  build_test: '>=1.3.7'
