name: tekartik_html
version: 0.3.1
description: An html abstraction layer to work with both dart:html and the html package
homepage: https://github.com/tekartik/tekartik_html.dart
publish_to: none

environment:
  sdk: ^3.9.0
dependencies:
  args: ">=2.6.0"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.7'
  html: '>=0.15.0'
  web: '>=0.5.0'

dev_dependencies:
  test: ">=1.24.0"
  dev_build: ">=1.1.2"
  process_run: ">=1.2.1+1"
  build_runner: ">=2.4.13"
  build_web_compilers: ">=4.0.11"
  build_test: '>=1.3.7'

dependency_overrides:
  web: '>=1.0.0'
